# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:2.12-2.2.0
        environment:
         KAFKA_ADVERTISED_HOST_NAME: localhost
         KAFKA_ADVERTISED_PORT: 9092
         KAFKA_PORT: 9092
         KAFKA_ZOOKEEPER_CONNECT: localhost:2181
         KAFKA_DELETE_TOPIC_ENABLE: true
         KAFKA_SUPER_USERS: User:ANONYMOUS
         KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      - image: wurstmeister/kafka:2.12-2.2.0
        environment:
         KAFKA_ADVERTISED_HOST_NAME: localhost
         KAFKA_ADVERTISED_PORT: 9093
         KAFKA_PORT: 9093
         KAFKA_ZOOKEEPER_CONNECT: localhost:2181
         KAFKA_DELETE_TOPIC_ENABLE: true
         KAFKA_SUPER_USERS: User:ANONYMOUS
         KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew test